### ISSUE TITLE
comparison of `im` to `iw`

### ISSUE THREAD

**Issue by Konfekt** [D4KU/vim-textobj-chainmember#1]
Your examples show clearly why `i.` falls short, but could you give another one where `iw` falls short as well?

**Comment by D4KU** [comment]
How about this case: imagine the cursor somewhere over "second":

diw yields first.~~second~~(arg1.var, foo()).third
di. yields first.~~second(arg1~~.var, foo()).third
dim yields first.~~second(arg1.var, foo())~~.third

**Comment by Konfekt** [comment]
Thank you, that makes sense

**Comment by D4KU** [comment]
You're welcome ;)
